name: Deploy to Vercel

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Vercel CLIをインストール
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Vercelにデプロイ
      - name: Deploy to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
